-- Auto-generated from data/orders.json, data/customers.json, data/staff.json
DELETE FROM orders; DELETE FROM customers; DELETE FROM staff;

INSERT INTO orders (id, customer_name, customer_phone, event_date, status, created_at, seq, data) VALUES ('ADVKM-0001', 'Laxman', '', NULL, 'pending', '2026-06-30', 1, '{"id": "ADVKM-0001", "customer": {"name": "Laxman", "phone": "", "type": "older", "address": "", "location": null}, "serviceType": "tenthouse", "program": {"type": "", "name": "", "imageUrl": ""}, "eventDate": null, "status": "pending", "createdAt": "2026-06-30", "legacyItems": [{"label": "6x10 tent", "qty": "1"}, {"label": "4x8 tent (big)", "qty": "1"}, {"label": "Gas: 50kg", "qty": "2"}, {"label": "Gas: 30kg", "qty": "1"}, {"label": "Gas: 25kg", "qty": "1"}, {"label": "Gas: 20kg", "qty": "1"}, {"label": "Gas: 10kg", "qty": "2"}, {"label": "Chairs", "qty": "60"}, {"label": "Drum", "qty": "2"}, {"label": "LED", "qty": "2"}, {"label": "Poles", "qty": "4"}, {"label": "Bakitlu (buckets)", "qty": "6"}, {"label": "Thatlu (plates)", "qty": "6"}, {"label": "Jug", "qty": "2"}, {"label": "Jallithati", "qty": "2"}, {"label": "Kabgir", "qty": "3"}, {"label": "Tables, big", "qty": "2"}, {"label": "Tables, small", "qty": "2"}, {"label": "Sidewalls", "qty": "2"}], "tenthouse": null, "decoration": null, "staffAssigned": [], "invoice": {"totalAmount": "", "advancePaid": "", "paymentType": ""}, "notes": ""}');
INSERT INTO orders (id, customer_name, customer_phone, event_date, status, created_at, seq, data) VALUES ('ADVKM-0002', 'Bongurapu Satish (mama)', '', '2026-06-07', 'pending', '2026-06-07', 2, '{"id": "ADVKM-0002", "customer": {"name": "Bongurapu Satish (mama)", "phone": "", "type": "older", "address": "", "location": null}, "serviceType": "decoration", "program": {"type": "Birthday", "name": "", "imageUrl": ""}, "eventDate": "2026-06-07", "status": "pending", "createdAt": "2026-06-07", "legacyItems": [{"label": "Wire LED, blue (metallic)", "qty": "20"}, {"label": "8x4 frames (white)", "qty": "6"}, {"label": "Background cloth", "qty": "1"}, {"label": "White small tickly", "qty": "1"}, {"label": "White large tickly", "qty": "8"}, {"label": "Wire box", "qty": "1"}, {"label": "Happy Birthday string", "qty": "1"}, {"label": "Iron stands, small", "qty": "2"}, {"label": "Sidewalls (blue)", "qty": "2"}, {"label": "Mats", "qty": "3"}, {"label": "Flower sheets", "qty": "3"}, {"label": "LED light + power coin (night)", "qty": "1 + 2"}, {"label": "Sofa (white)", "qty": "1"}, {"label": "Boxes, small (DJ)", "qty": "-"}, {"label": "Round ring (3 feet)", "qty": "-"}], "tenthouse": null, "decoration": null, "staffAssigned": [], "invoice": {"totalAmount": "", "advancePaid": "", "paymentType": ""}, "notes": ""}');
INSERT INTO orders (id, customer_name, customer_phone, event_date, status, created_at, seq, data) VALUES ('ADVKM-0003', 'Ch. Karunakar', '', '2026-07-10', 'pending', '2026-07-09', 3, '{"id": "ADVKM-0003", "customer": {"name": "Ch. Karunakar", "phone": "", "type": "older", "address": "", "location": null}, "serviceType": "tenthouse", "program": {"type": "", "name": "", "imageUrl": ""}, "eventDate": "2026-07-10", "status": "pending", "createdAt": "2026-07-09", "legacyItems": [{"label": "4x8 tent, big (old)", "qty": "1", "note": "Radhabhai valla kada"}, {"label": "3x6 tent (old)", "qty": "1", "note": "same 1st day"}, {"label": "Gas: 50kg (soda)", "qty": "1"}, {"label": "Gas: 25kg", "qty": "2"}, {"label": "Gas: 30kg (lagan)", "qty": "1"}, {"label": "Bakitlu (buckets)", "qty": "4-4"}, {"label": "Thatlu (plates)", "qty": "4-4"}, {"label": "Curry donga, big", "qty": "1"}, {"label": "Jallithati", "qty": "1"}, {"label": "Jug", "qty": "4"}, {"label": "Tables, big", "qty": "2"}, {"label": "Tables, small", "qty": "1"}, {"label": "Chairs", "qty": "20"}, {"label": "Kabgir", "qty": "2"}, {"label": "Saratham", "qty": "1"}, {"label": "Drum", "qty": "2"}], "tenthouse": null, "decoration": null, "staffAssigned": [], "invoice": {"totalAmount": "", "advancePaid": "", "paymentType": ""}, "notes": ""}');
INSERT INTO orders (id, customer_name, customer_phone, event_date, status, created_at, seq, data) VALUES ('ADVKM-0004', 'Pulla Srinivas', '', '2026-07-25', 'pending', '2026-07-25', 4, '{"id": "ADVKM-0004", "customer": {"name": "Pulla Srinivas", "phone": "", "type": "older", "address": "", "location": null}, "serviceType": "tenthouse", "program": {"type": "Festival''s", "name": "Yellamma temple, Eduougatla", "imageUrl": ""}, "eventDate": "2026-07-25", "status": "pending", "createdAt": "2026-07-25", "legacyItems": [{"label": "DJ boxes (200)", "qty": "1 set"}, {"label": "Mic", "qty": "1"}, {"label": "LED", "qty": "2"}, {"label": "Wire box", "qty": "3"}, {"label": "Tables", "qty": "2"}, {"label": "Gas: 20kg", "qty": "1"}, {"label": "Gas: 10kg", "qty": "3"}, {"label": "Thatlu (plates)", "qty": "2-2"}, {"label": "Bakitlu (buckets)", "qty": "2-2"}, {"label": "Jallithati", "qty": "1"}, {"label": "Kabgir", "qty": "1"}, {"label": "Jug", "qty": "2"}, {"label": "Curry donga", "qty": "1"}], "tenthouse": null, "decoration": null, "staffAssigned": [], "invoice": {"totalAmount": "", "advancePaid": "", "paymentType": ""}, "notes": ""}');
INSERT INTO customers (id, name, phone, data) VALUES ('laxman', 'Laxman', '', '{"id": "laxman", "name": "Laxman", "phone": "", "type": "older"}');
INSERT INTO customers (id, name, phone, data) VALUES ('bongurapu-satish', 'Bongurapu Satish (mama)', '', '{"id": "bongurapu-satish", "name": "Bongurapu Satish (mama)", "phone": "", "type": "older"}');
INSERT INTO customers (id, name, phone, data) VALUES ('ch-karunakar', 'Ch. Karunakar', '', '{"id": "ch-karunakar", "name": "Ch. Karunakar", "phone": "", "type": "older"}');
INSERT INTO customers (id, name, phone, data) VALUES ('pulla-srinivas', 'Pulla Srinivas', '', '{"id": "pulla-srinivas", "name": "Pulla Srinivas", "phone": "", "type": "older"}');
INSERT INTO staff (id, name, phone, data) VALUES ('shivaji', 'Shivaji', '', '{"id": "shivaji", "name": "Shivaji", "phone": "", "assignments": []}');
INSERT INTO staff (id, name, phone, data) VALUES ('ashwin', 'Ashwin', '', '{"id": "ashwin", "name": "Ashwin", "phone": "", "assignments": []}');
INSERT INTO staff (id, name, phone, data) VALUES ('kitty', 'Kitty', '', '{"id": "kitty", "name": "Kitty", "phone": "", "assignments": []}');
INSERT INTO staff (id, name, phone, data) VALUES ('bhagya', 'Bhagya', '', '{"id": "bhagya", "name": "Bhagya", "phone": "", "assignments": []}');
INSERT INTO staff (id, name, phone, data) VALUES ('sathwika', 'Sathwika', '', '{"id": "sathwika", "name": "Sathwika", "phone": "", "assignments": []}');
INSERT INTO staff (id, name, phone, data) VALUES ('abhiram', 'Abhiram', '', '{"id": "abhiram", "name": "Abhiram", "phone": "", "assignments": []}');
INSERT INTO staff (id, name, phone, data) VALUES ('vinay', 'Vinay', '', '{"id": "vinay", "name": "Vinay", "phone": "", "assignments": []}');
